package objects;

public enum AccountAction {
	SellBTC,
    BuyBTC,
    FeeBuyBTC,
    FeeSellBTC,
    DepositBTC,
    DepositNIS,
    WithdrawalBTC,
    WithdrawalNIS,
    FeeWithdrawalBTC,
    FeeWithdrawalNIS,
    Unknown,
    PayWithBTC,
    ReceivedPaymentBTC,
    FeeReceivedPaymentBTC,
    DepositLTC,
    WithdrawalLTC,
    FeeWithdrawalLTC,
    BuyLTCBTC,
    SellLTCBTC,
    BuyLTCNIS,
    SellLTCNIS,
}
